Split code + Add utility package
asen23/TodoListOOP pull request #2
Opened 2022-06-02 16:43 UTC by MikazukiMizuki

Memisahkan menu menjadi tagmenu dan todomenu, lalu menambahkan interface dan package helper

2022-06-02 16:57 UTC, asen23 commented on src/helper/PrintHelp.java
> +public class PrintHelp {
Sebaiknya kelas ini jadiin static semua aj ya biar gausah diinit
atau misalkan ga statik jadiin singleton

2022-06-02 16:57 UTC, asen23 commented on src/menu/TagMenu.java
> +            choice = scan.nextInt();
sebaiknya validasi dlu pake scan.HasNext sama scan.HasNextInt
lupa kasihtau denzel gw ini

2022-06-02 16:57 UTC, asen23 commented on src/menu/Menu.java
> +                    toDo.todoMenu();
biar namanya ga dupli mending jadi toDo.menu()
yg tag juga sama

2022-06-02 16:57 UTC, asen23 commented on src/menu/TagMenu.java
> +		ph.printSeparator();
benerin indentnya

2022-06-02 16:57 UTC, asen23 commented on src/menu/ToDoMenu.java
> +        	printMenuList();
benerin indentnya

2022-06-02 16:57 UTC, asen23 commented on src/menu/ToDoMenu.java
> +		ph.printSeparator();
benerin indentnya

2022-06-02 16:57 UTC, asen23 requested changes
dibenerin dlu ya

2022-06-02 17:14 UTC, MikazukiMizuki commented on src/menu/TagMenu.java
> +		ph.printSeparator();
Indentasi default eclipse gw kyk gini sih
nanti gw coba ke indentasi vs code

2022-06-04 13:48 UTC, asen23 approved these changes

2022-06-04 13:49 UTC, merged